### ISSUE TITLE
reason for requiring PHP >= 7.0?

### ISSUE THREAD

**Issue by ghost** [mollie/polyfill-libsodium#1]
Is there a particular reason for requiring PHP 7.0? On RHEL/CentOS EPEL and Fedora php-pecl-libsodium 1.x is used which still has the `\Sodium` namespace version. As you check for availability of `\Sodium` in `bootstrap.php` it could also work on PHP >= 5.4 or maybe even lower that used php-libsodium 1.x? Am I missing something?

**Comment by willemstuursma** [comment]
It's because the typehints that are present in the polyfill, but they could be removed. Pull requests are totally welcome.
